disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
included:
  - apps
  - packages
opt_in_rules:
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
reporter: xcode





